### ISSUE TITLE
IPlayerManager.RetrieveAsync completely locks up

### ISSUE THREAD

**Issue by BowDown097** [angelobreuer/Lavalink4NET#129]
**Describe the bug**
After migrating to V4, using IPlayerManager.RetrieveAsync completely locks up my Discord bot and leads to "A MessageReceived handler is blocking the gateway task." This never happened with the older IAudioService.GetPlayer.

Doing some debugging traced the issue to [this line](https://github.com/angelobreuer/Lavalink4NET/blob/673e7c10ae257a0c12b14b2d283e4b8ff66c0aaa/src/Lavalink4NET/Players/LavalinkPlayerHandle.cs#L83). Not sure what to do beyond this point.

**To Reproduce**
I'll give a basic outline of what is done in my code up to this point, but if you want to look in detail, I have it up [here](https://github.com/BowDown097/RRBot/tree/lavalink-v4).

1. Set up a host builder's services as such, where client is a DiscordShardedClient, DiscordClientHost is an IHostedService that sets up the bot appropriately, and AudioSystem is a control center for Lavalink actions that will be described next:
```cs
builder.Services
    .AddSingleton(client)
    .AddSingleton<CommandService>()
    .AddSingleton<InteractionService>()
    .AddSingleton<InteractiveService>()
    .AddHostedService<DiscordClientHost>()
    .AddLavalink()
    .AddLogging()
    .AddInactivityTracking()
    .ConfigureInactivityTracking(options => options.DefaultTimeout = TimeSpan.FromSeconds(Constants.InactivityTimeoutSecs))
    .AddSingleton<AudioSystem>();
```
2. Create a Music Discord.Net module with the aforementioned AudioSystem as a property to connect it and some bot commands together - the commands themselves I'm pretty sure aren't important.
3. Set up the AudioSystem as a public sealed class with this:
```cs
private readonly IAudioService _audioService;
private static readonly IOptions<VoteLavalinkPlayerOptions> PlayerOptions = Options.Create(new VoteLavalinkPlayerOptions());
public AudioSystem(IAudioService audioService) => _audioService = audioService;
```
4. Create a method to get a player inside of the AudioSystem as such:
```cs
private async ValueTask<PlayerResult<VoteLavalinkPlayer>> GetPlayerAsync(
    SocketCommandContext context,
    PlayerChannelBehavior channelBehavior = PlayerChannelBehavior.None,
    ImmutableArray<IPlayerPrecondition> preconditions = default)
{
    SocketGuildUser guildUser = context.User as SocketGuildUser;
    PlayerRetrieveOptions retrieveOptions = new(
        ChannelBehavior: channelBehavior,
        Preconditions: preconditions,
        VoiceStateBehavior: MemberVoiceStateBehavior.RequireSame
    );

    return await _audioService.Players.RetrieveAsync(
        context.Guild.Id,
        guildUser.VoiceChannel.Id,
        PlayerFactory.Vote,
        PlayerOptions,
        retrieveOptions
    );
}
```
5. Immediate lock-up upon any usage of GetPlayerAsync.

**Expected behavior**
The function retrieves an appropriate player without any kind of lock-up.

**Information**
 - Lavalink4NET Version: 4.0.0-beta.3-6
 - Lavalink Version: 4.0.0-beta.5, also tested with 4.0.0-beta.3 just in case
 - Exception thrown? (consider enabling logging): Nothing is logged at all following RetrieveAsync being called outside of the aforementioned gateway task error, even on the Trace log level.

**Additional context**
Here's the logs on Trace mode (with compromising stuff removed) though I don't think they will help any: [logs.txt](https://github.com/angelobreuer/Lavalink4NET/files/13453211/logs.txt)

**Comment by angelobreuer** [comment]
Thank you for your impressively detailed issue request. I did not investigate in-depth but I wanted to share my initial thought:

Since you are on the message received handler, this means you are operating on the gateway thread, which means that basically all messages sent to the bot during that operation are blocked. 

Since you are using RetrieveAsync, you are actually trying to connect the bot to the voice channel. The problem is, that L4N needs to send a voice update to the discord gateway (this works fine) but it also needs to receive two events. Remember, we are on the message received handler, i.e. we do not get any messages anymore from the gateway. Now, we have a deadlock scenario, that means we are waiting for new events to be dispatched, however that is not possible since the gateway handler is waiting for us to complete the message received handler.

There are two simple solutions to that (in case this really is your issue):
- If you do not want to actually _connect_ the player to the channel, then you can simply use `TryGetPlayer` on the player manager.
- If you actually need to connect the player, then the problem is that we can not keep blocking the message received handler and we need to do the work somewhere else. You could asynchronously dispatch the task, or somehow enqueue the procession of that.

**Comment by angelobreuer** [comment]
And probably a (better) third option:

It seems like that you are using the command library of your bot framework, Discord.Net. There is a thing called the "Run Mode" of a command which either decides if commands should block on the gateway thread, or if they should be dispatched asynchronously. You can also fix the problem by setting the run mode to be `Async`. 

```cs
[SlashCommand("test", "A sample description", runMode: RunMode.Async)]
public async Task TestCommand(string test)
{
}
```

**Comment by angelobreuer** [comment]
To provide more explanation:

> This never happened with the older IAudioService.GetPlayer.

The `GetPlayer` and `RetrieveAsync` methods are quite different. The `RetrieveAsync` method does tons of things at once to make your life easier (or at least it should). It checks certain preconditions, can get the current player, or creates a new one if needed. The _old_ `GetPlayer` method simply did only one thing: Check if the player exists, if so return it, if not return `null`.

You can use the more modern `TryGetPlayer` instead of the old (and no longer existent) `GetPlayer` if you want a direct replacement. `RetrieveAsync` is a combination of `TryGetPlayer` and `JoinAsync` while also doing some other things.

**Comment by BowDown097** [comment]
Yep, that appears to have been the issue. Big thanks man. Would probably be a good idea to put a note for that somewhere in the migration guide.

Also side suggestion, ICommandContext overloads for RetrieveAsync would be cool since they exist for IInteractionContext. Surprised Discord.NET doesn't have a base interface they both derive from since their properties are nearly identical but whatever.

**Comment by angelobreuer** [comment]
I will add this to the documentation some time, glad that the above helped

**Comment by angelobreuer** [comment]
> Also side suggestion, ICommandContext overloads for RetrieveAsync would be cool since they exist for IInteractionContext. Surprised Discord.NET doesn't have a base interface they both derive from since their properties are nearly identical but whatever.

This will be included in the next release
