### ISSUE TITLE
Bug: Player parameters not taken into account.

### ISSUE THREAD

**Issue by Simnico99** [angelobreuer/Lavalink4NET#130]
**Describe the bug**
It doesn't seem to take into account my parameters of self-deaf and initial volume when creating a new player using the RetrieveAsync method. I've looked at the code of the LavalinkPlayer and it seems to not set those on the constructor either. Am I doing something wrong?

**To Reproduce**
Create a new player using the RetrieveAsync

**Expected behavior**
SelfDeaf and SelfMute parameters should be taken into account.

**Screenshots**

**(please complete the following information):**
 - Lavalink4NET (4.0.0-beta.3.6)
 - Exception thrown? None.

**Additional context**
Here is an exemple of what I do:
```csharp
var playerResult = await _audioService.Players.RetrieveAsync(message.Context, playerFactory: PlayerFactory.Create<LoopingQueuedLavalinkPlayer, QueuedLavalinkPlayerOptions>(properties =>
{
    properties.Options.Value.SelfDeaf = true;
    properties.Options.Value.InitialVolume = 0.5f;
     return new LoopingQueuedLavalinkPlayer(properties);
}), retrieveOptions);
```

**Comment by angelobreuer** [comment]
Hello @Simnico99,

in the first, I was not able to reproduce the issue as presented above:

```cs
var audioService = app.Services.GetRequiredService<IAudioService>();

var retrieveOptions = new PlayerRetrieveOptions { ChannelBehavior = PlayerChannelBehavior.Join, };

void Configure(QueuedLavalinkPlayerOptions options)
{
    options.SelfDeaf = true;
}

var player = await audioService.Players
    .RetrieveAsync(context, PlayerFactory.Queued,Configure, retrieveOptions)
    .ConfigureAwait(false);
```

This resulted in the player being deafened as wanted:

![image](https://github.com/angelobreuer/Lavalink4NET/assets/46497296/7adaeb90-37f5-4d99-bcd0-84b9c000fd8e)

When I took a closer look at your code, it seems like there is an issue with how the options are passed:

```cs
var playerResult = await _audioService.Players.RetrieveAsync(message.Context, playerFactory: PlayerFactory.Create<LoopingQueuedLavalinkPlayer, QueuedLavalinkPlayerOptions>(properties =>
{
    properties.Options.Value.SelfDeaf = true;
    properties.Options.Value.InitialVolume = 0.5f;
     return new LoopingQueuedLavalinkPlayer(properties);
}), retrieveOptions);
```

In the above code, you create a custom player factory to create your player. This is fine, however, you are also modifying the options of that player which is not allowed in the player factory. You should only consume the options provided by the player options.

The intended way is to create your options and pass it to the `.RetrieveAsync` method. You can then consume the options in your player factory.

So let us fix the code:

First, we will split the player factory to make it easier to understand:

```cs
var playerFactory = PlayerFactory.Create<LoopingQueuedLavalinkPlayer, QueuedLavalinkPlayerOptions>(properties =>
{
    properties.Options.Value.SelfDeaf = true;
    properties.Options.Value.InitialVolume = 0.5f;
     return new LoopingQueuedLavalinkPlayer(properties);
});

var playerResult = await _audioService.Players.RetrieveAsync(message.Context, playerFactory, retrieveOptions);
```

Now, we remove the options modification, since, as said above this is not allowed. We should only construct the player in the player factory:

```cs
var playerFactory = PlayerFactory.Create<LoopingQueuedLavalinkPlayer, QueuedLavalinkPlayerOptions>(
    properties => new LoopingQueuedLavalinkPlayer(properties));

var playerResult = await _audioService.Players.RetrieveAsync(message.Context, playerFactory, retrieveOptions);
```

However, we still, of course, want to apply the player options:

```cs
var playerOptions = new QueuedLavalinkPlayerOptions
{
    SelfDeaf = true,
    InitialVolume = 0.5F,
};

var playerFactory = PlayerFactory.Create<LoopingQueuedLavalinkPlayer, QueuedLavalinkPlayerOptions>(
    properties => new LoopingQueuedLavalinkPlayer(properties));

var playerResult = await _audioService.Players.RetrieveAsync(message.Context, playerFactory, playerOptions, retrieveOptions);
```

I will provide some technical background about why this issue occurs although you modify the self-deaf property in the player factory. The `.RetrieveAsync` method will check whether the current state matches with the parameters you have specified in the arguments when you call the method. In case, the bot should be connected to the channel, L4N will instruct the discord client to tell the discord gateway to join that channel (with self-deaf and self-mute information). After the state has been confirmed, the player will be created. Since you are using the player factory, your custom code will be called. Now, your modifications on the options come into action. But when you look at the order how everything occurred, your option modifications will have no affect since they were applied before you did change them.

**Comment by angelobreuer** [comment]
Please reopen if the above answer did not solve this issue

**Comment by Simnico99** [comment]
Thank you for your detailed answer it helps me understand the new pipeline. I was looking at the documentation and didn't find the information that is why I opened up an issue. To be honest I thought it was probably my implementation and it actually was.

Thanks for helping!
![image](https://github.com/angelobreuer/Lavalink4NET/assets/80013536/e975f0bc-cfe4-4532-b09b-8924f9ea8012)
