### ISSUE TITLE
DisposeAsyncCore seems to get fired multiple times

### ISSUE THREAD

**Issue by BlyZeDev** [angelobreuer/Lavalink4NET#140]
**Describe the bug**
I have overriden the DisposeAsyncCore method of the QueuedLavalinkPlayer, so that it sends an embed automatically when the Bot disconnects.

```cs
protected override async ValueTask DisposeAsyncCore()
{
    await base.DisposeAsyncCore();
    
    await Options.TextChannel.SendEmbedAsync(Embeds.GetDisconnected());
}
```

**To Reproduce**
1. The bot leaves the voice channel for whatever reason.
2. The Disconnect embed gets send twice sometimes.

**Expected behavior**
The embed is only send once

**(please complete the following information):**
 - Lavalink4NET Version: 4.0.9
 - Exception thrown? No

**Comment by BlyZeDev** [comment]
Maybe thats not the way i should use to do this but I didn't find a other way for this.

**Comment by angelobreuer** [comment]
This is intended behavior, the `DisposeAsync` pattern is a bit different instead of using `Dispose` alone due to various reasons. If `LavalinkPlayer` would only implement `IDisposable`, you could expect `Dispose(bool)` only to be called once (at least if the implementation is compliant). However with `IAsyncDisposable` the convention has been changed because there might be also an implementation for `IDisposable` which would need to be called differently.
Check here for more reference: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync

To solve that you will need to implement checking whether the player has been already disposed or not. I would recommend you to have a dedicated flag (`bool`) field to check whether the embed has been sent or not. 

---

Microsoft recommends the `DisposeAsync` method to be implemented like this:

```cs
public async ValueTask DisposeAsync()
{
    // Perform async cleanup.
    await DisposeAsyncCore();

    // Dispose of unmanaged resources.
    Dispose(false);

    // Suppress finalization.
    GC.SuppressFinalize(this);
}
```

The first pass will clean all asynchronously disposable resources and the second pass will clean up all synchronously disposable resources (but mostly some of them, because mostly DisposeAsync will take care of them).

---

The following is the implementation of the `DisposeAsyncCore` method of the `LavalinkPlayer` which does the checking in that method:

```cs
protected virtual async ValueTask DisposeAsyncCore()
{
    if (Interlocked.CompareExchange(ref _disposed, 1, 0) is not 0)
    {
        return;
    }

    await UpdateStateAsync(PlayerState.Destroyed).ConfigureAwait(false);

    // Dispose the lifecycle to notify the player is being destroyed
    await using var _ = _playerLifecycle.ConfigureAwait(false);

    _logger.PlayerDestroyed(Label);

    await ApiClient
        .DestroyPlayerAsync(SessionId, GuildId)
        .ConfigureAwait(false);

    if (_disconnectOnDestroy)
    {
        await DiscordClient
            .SendVoiceUpdateAsync(GuildId, null, false, false)
            .ConfigureAwait(false);
    }
}
```

**Comment by angelobreuer** [comment]
To add some information about why the issue might occur in the first place:

In any case, `DisposeAsyncCore` could be fired as many times as the API wants to do so. However, Lavalink4NET may dispose players from various places and the player is disposed once on clean up by the player lifecycle as well as by the client itself. However, depending on the stop reason, it might be also disposed by the inactivity tracking which then only disposes the player lifecycle as well. Additionally, it could be possible that it might be disposed by a player node movement, which then however, does not actually stop the voice connection. So there is no real guarantee for the player being disposed in a specific way or from a specific caller, it more depends on the purpose of the player destroy.

**Comment by BlyZeDev** [comment]
Okay, I'll do that, thank you for helping :)
