### ISSUE TITLE
OnTrackEndAsync not fired after reconnect to node

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#24]
**Describe the bug**
OnTrackEndAsync not fired after reconnect to node

**To Reproduce**
1. Start bot
2. Wait for connecting to lavalink
3. Shutdown lavalink server
4. Start lavalink server
5. Wait for connecting to lavalink

**Expected behavior**
I expected that after re-joining everything would work as intended.

 - Lavalink4NET Version 1.4.6

**Additional context**
Instead of steps 4-5, there may simply be any break in the connection of the bot and lavalink

**Comment by angelobreuer** [comment]
Hello @SKProCH, thanks for your report!

There was a related issue in the Receive Loop after reconnecting to the Lavalink Node, see [#22 Nodes stop trying to reconnect after reconnecting once](https://github.com/angelobreuer/Lavalink4NET/issues/22), which was fixed in Lavalink4NET Version 1.4.8 ([NuGet](https://www.nuget.org/packages/Lavalink4NET/1.4.8)). 

Does Lavalink4NET Version 1.4.8 solve your issue?

Thanks in advance.

**Comment by SKProCH** [comment]
Yes, I updated the library, and it seems like everything works. I apologize for this issue.

But there is one more problem: sometimes after a node disconnects, it does not try to connect back to it. Should I make a separate issue for this?

**Comment by angelobreuer** [comment]
> Yes, I updated the library, and it seems like everything works. I apologize for this issue.

Good to know, thanks!

> But there is one more problem: sometimes after a node disconnects, it does not try to connect back to it. Should I make a separate issue for this?

Yes, please. I would appreciate it. Thanks.
