### ISSUE TITLE
QueuedLavalinkPlayer refuses to play after using GetTracksAsync()

### ISSUE THREAD

**Issue by Swyreee** [angelobreuer/Lavalink4NET#91]
**Describe the bug**
The title says it all.

**To Reproduce**
(using DSharpPlus 4.2.0-nightly-1079 with DSharpPlus.SlashCommand)
- `_client.Lavalink` is the DI'ed Lavalink client
```c#
[SlashCommand("pltest", "Playlist test command")]
public async Task MusicPlTestCmd(InteractionContext ctx) {
  await ctx.DeferAsync();

  await ctx.EditResponseAsync(new DiscordWebhookBuilder()
    .WithContent("Executing"));

  var player = await _client.Lavalink.JoinAsync < QueuedLavalinkPlayer > (ctx.Guild.Id, ctx.Member.VoiceState.Channel.Id, true);

  var tracks = await _client.Lavalink.GetTracksAsync("https://www.youtube.com/playlist?list=PL_h4IoimLDtTBLxUn8vJBq3DVsoHcwsJa");
  player.Queue.AddRange(tracks);
  var track2 = player.Queue.Dequeue();

  await player.PlayAsync(track2);
}
```

**Expected behavior**
The queued player should play from begin to end of the queue normally.

**Screenshots**
- No `play` opcode is sent after calling PlayAsync()
![image](https://user-images.githubusercontent.com/41561710/154920963-ad737d33-249a-4465-9ac6-042eda2fcb37.png)

**(please complete the following information):**
 - Lavalink4NET Version: 2.1.1-preview.3
 - Exception thrown? None

**Additional context**
- Lavalink still decodes the playlist
![image](https://user-images.githubusercontent.com/41561710/154919798-a4010aa7-33ae-41e9-8c8f-ad2c0e3d2637.png)
![image](https://user-images.githubusercontent.com/41561710/154920369-f9afbd89-ce7a-47c9-b328-1f9d29160375.png)
- The queue works fine
![image](https://user-images.githubusercontent.com/41561710/154922062-6a6ece63-e3a3-4feb-b4ab-b8ccdad788a1.png)

**Comment by angelobreuer** [comment]
Hello @Swyreee ,

thank you for your issue! 

This seems strange, I think you are using the `GetTrackAsync` method (without the `s`) in a play Method. Does this work, or is there the same problem as when using `GetTracksAsync`? The `GetTrackAsync` method uses `GetTracksAsync` under the hood.

Could you try to use the following snippet, and see if it works?

```csharp
var player = await _client.Lavalink.JoinAsync < QueuedLavalinkPlayer > (ctx.Guild.Id, ctx.Member.VoiceState.Channel.Id, true);

var tracks = await _client.Lavalink.GetTracksAsync("https://www.youtube.com/playlist?list=PL_h4IoimLDtTBLxUn8vJBq3DVsoHcwsJa");
player.Queue.AddRange(tracks);

if (tracks.Any())
{
  await player.SkipAsync(); // tells the player to take the first song, and start it
}
```

Is there any exception that is thrown? (I don't know Rider that much, there should be an equivalent to the output window of Visual Studio, that shows thrown but smallowed exceptions).

**Comment by Swyreee** [comment]
Hi @angelobreuer, thank you for reaching me.

With your provided code snippet, the player works as expected.

Also I tried `GetTrackAsync` with the following code snippet, the player worked fine:
```c#
var player = await _client.Lavalink.JoinAsync<QueuedLavalinkPlayer>(ctx.Guild.Id, ctx.Member.VoiceState.Channel.Id, true);

var track1 = await _client.Lavalink.GetTrackAsync("https://www.youtube.com/watch?v=SItIaWAjI_4");
player.Queue.Add(track1);

var track2 = player.Queue.Dequeue();
await player.PlayAsync(track2);
```

Additionally, when I use this workflow, the playlist addition works as expected:
- Create a queued player
- Add single song to queue
- Play the queue
- Add a playlist to queue
- Leave it there, it will play everything in the queue

**Comment by angelobreuer** [comment]
I think I've found the problem. When you add for example 100 tracks to the queue, then dequeue the top track, add try to play it, nothing happens. This is because when you dequeue the track, the track is removed from the top of the queue, and at the moment you want to play it, it is added to the bottom of the queue. This is because the player thinks, it should not play anything, because you only want to enqueue the track. The difference of the behavior of the unqueued lavalink player, and the queued lavalink player, is that if there are tracks, enqueued, then the queued lavalink player, will not play the track, but it will add the track to the queue. It is intentional that the player does not directly start playing the track, because there may be the case, that you do not want to start playing, but add items to the queue. For that reason, there is a `enqueue` parameter on an extra overload of the queued lavalink player. Change your call `await player.PlayAsync(track2);` to `await player.PlayAsync(track2, euqueue: true);`, or use the add queue-skip approach, I mentioned earlier.

**Comment by Swyreee** [comment]
Tried the changes you mentioned and it worked fine now, I guess I should close this issue now, thank a lot.

Feel free to reopen the issue as you wish!

Have a good day.
